### ISSUE TITLE
Many nanopubs have URIs in identifier.org domain

### ISSUE THREAD

**Issue by tkuhn** [wikipathways/nanopublications#9]
Many nanopubs have identifiers in the identifier.org domain, for which we have no authority to mint new URIs. For example: http://identifiers.org/tair.locus/AT3G21720_nanopub.RA9T4XOYC3lwM5Qqz-Poyj5JPKK7ylpO6a_T8AvJxVd7o

**Comment by egonw** [comment]
Still need to look at this...

**Comment by egonw** [comment]
@tkuhn, can you please check the .trig files here: https://jenkins.bigcat.unimaas.nl/job/WikiPathways%20Nanopublications/ws/

I have applied your suggestion, and all (not just the interactions) nanopubs are into purl.org/np/ range...
If it looks good to you, then I will make updated history nanopubs.

**Comment by tkuhn** [comment]
The identifier part looks good, but each file now seems to contain just one nanopublication, with too many triples included. It seems some unintentional nanopub merging is going on?

**Comment by egonw** [comment]
Ah, but that is because of the way the system is set up... I need to think about this... the system is as follows:

1. SPARQL CONSTRUCT queries make resources
2. each resource is then converted to a nanopub

So, that's why it had those weird IRIs: they were based on data I have in the WPRDF... I replaced that with purl.org/np/ IRIs, but forgot that that was at the intermediate RDF layer (after WPRDF, before NanoPubs)... I cannot easily make up IRIs with SPARQL CONSTRUCT and need to think about this...

**Comment by tkuhn** [comment]
Can't you create the resources as before, but then use purl.org/np/ as identifiers for the nanopubs?

**Comment by egonw** [comment]
Not trivial to do in SPARQL CONSTRUCT but exactly what I'm trying to do since about an hour... hang one ;)

**Comment by egonw** [comment]
OK, I think I have it working... confirmation soon.
